### ISSUE TITLE
Edge browser detected as Chrome.

### ISSUE THREAD

**Issue by johnrizzo4** [muaz-khan/DetectRTC#113]
In this article from 2019, the Microsoft team explains why they replaced "Edge" by "Edg" in the userAgent string.
https://blogs.windows.com/msedgedev/2019/04/08/microsoft-edge-preview-channel-details/
Look for the subtitle "User Agent String"

getBrowserInfo..js is looking for "Edge" instead of "Edg" at line 3:

```
var isEdge = navigator.userAgent.indexOf('Edge') !== -1 && (!!navigator.msSaveOrOpenBlob || !!navigator.msSaveBlob);
```

My suggested replacement:

```
var isEdge = (navigator.userAgent.indexOf('Edge') !== -1 || navigator.userAgent.indexOf('Edg') !== -1) // Microsoft replaced 'Edge' by 'Edg' a while ago to avoid confusion with a legacy Edge browser.
             && (!!navigator.msSaveOrOpenBlob || !!navigator.msSaveBlob);

```

This recent article shows similar code with "Edg": https://codepedia.info/detect-browser-in-javascript

I guess that this is why Edge is identified as Chrome by DetectRTC (since Edge also includes "Chrome" their string).
It's easy to see with https://www.webrtc-experiment.com/DetectRTC/ running from Edge as shown in this screenshot.

![image](https://user-images.githubusercontent.com/83981217/218373928-9acb3c06-32e5-4803-8880-d669cc13c7b8.png)

**Comment by David-dp-** [comment]
I just tested your suggested change in Edge Version 110.0.1587.41 (Official build) (64-bit). The first part of the AND succeeded but the second part was false. I tried each part in the console, too:
```
navigator.userAgent.indexOf('Edge')
-1
navigator.userAgent.indexOf('Edg')
112
navigator.msSaveOrOpenBlob
undefined
navigator.msSaveBlob
undefined
```
You should also use this updated line:
`var isChrome = !!window.chrome && !isEdge && !isOpera;`
And these:
```
fullVersion = navigator.userAgent.split(/Edge?\//)[1];
// fullVersion = parseInt(navigator.userAgent.match(/Edge?\/(\d+).(\d+)$/)[2], 10).toString();
```

**Comment by johnrizzo4** [comment]
I've updated the PR with your proposed changes, thank you David.

About navigator.msSaveOrOpenBlob and navigator.msSaveBlob, it's just a copy of the existing code. I don't understand the origin of that part which is not commented. I'll remove it from my PR as you suggest.

**Comment by junaiddarajat** [comment]
@johnrizzo4  I tried your PR, for macOS Monterey and Microsoft Edge Version 112.0.1722.68 (Official build) (x86_64); it's still showing as 'Chrome'. Should this be a proper case or maybe I'm doing something wrong?

EDIT: For using your PR, I've done the following at my React project's package.json dependencies:

```
        "detectrtc": "https://github.com/johnrizzo4/DetectRTC/#patch-issue-113-Edge-seen-as-Chrome",
```
